AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PowerLedger API written with SpringBoot and served on AWS Lambda

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  PowerLedgerApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.powerledger.api.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  PowerLedgerApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/batteries'
    Export:
      Name: PowerLedgerApi
